spring:
  datasource:
    url: jdbc:h2:file:./data/eventsdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
    defer-datasource-initialization: false
    open-in-view: false

  # ← Add SQL initialization config
  sql:
    init:
      mode: always  # ← Execute scripts for all database types
      schema-locations: classpath:schema.sql
      data-locations: [] # classpath:data.sql uncomment for dev testing and data initialization
      continue-on-error: false

  output:
    ansi:
      enabled: detect

# Clean logging
logging:
  level:
    com.jmb.events_api: INFO
    org.hibernate.SQL: WARN
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"